name: Generate docs, format and platforms

on:
  push:
    branches: ["main"]

jobs:
  docs-and-fmt:
    if: github.event != 'pull_request'
    name: Generate docs and format
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.NORDIC_BOT_APP_ID }}
          private-key: ${{ secrets.NORDIC_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v2
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Panvimdoc generate
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: nordic.nvim

      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=.stylua.toml .

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "CI(bot): Generate docs and format"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}

      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Generate platform files
        run: "./platforms.sh"
